# Generated by Django 4.1.2 on 2022-11-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Apartment', 'Apartment'), ('Building', 'Building')], max_length=16)),
                ('season', models.CharField(max_length=8)),
                ('month', models.CharField(max_length=8)),
                ('period', models.CharField(max_length=32)),
                ('ogr_povrs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('del_ogr_pov', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poraba', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kor_fakt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('osn_pd_13_clen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('korig_pd_15_1_clen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('korig_pd_povrs_15_4_clen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pod_40_nad_300_18_clen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prer_pd_100_19_clen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('var_del', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiks_del', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skp_del_poraba', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.apartment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.building')),
            ],
        ),
        migrations.CreateModel(
            name='Measurment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_number', models.BigIntegerField()),
                ('space', models.CharField(max_length=64)),
                ('initial_state', models.IntegerField()),
                ('final_state', models.IntegerField()),
                ('corr_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumption_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.consumptionreport')),
            ],
        ),
    ]
