# Generated by Django 4.1.2 on 2022-11-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_consumptionreport_measurment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionreport',
            name='season',
            field=models.CharField(max_length=16),
        ),
    ]
