# Generated by Django 4.1.2 on 2022-11-23 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_consumptionreport_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionreport',
            name='apartment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.apartment'),
        ),
        migrations.AlterField(
            model_name='consumptionreport',
            name='building',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.building'),
        ),
        migrations.AlterField(
            model_name='consumptionreport',
            name='kor_fakt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consumptionreport',
            name='skp_del_poraba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
