# Generated by Django 4.1.2 on 2022-11-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_consumptionreport_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionreport',
            name='kor_fakt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
